name: Workflow
on:
  push:
    branches:
      - feat-devsecops

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validando tipo de proyecto
      id: tipoProyecto
      run: |
        if [ -f "build.gradle" ]
        then
          echo "Proyecto Java"
          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
          then
            echo "El plugin de sonarCloud ya esta presente en build.gradle"
          else
            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
            echo "El plugin de sonarcloude no estaba presente y se ha aÃ±adido en build.gradle"
            cat build.gradle
          fi
        else
          echo "Tipo de proyecto desconocido"
        fi


    - name: Validando existencia de proyecto en SonarCloud
      id: validandoProjectOnSonar
      run: | 
        set +e
        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=dusankm' -d 'visibility=public'       
        if [ $? -ne 0 ]
        then
          echo "Proyecto ya existe en Sonarcloud"
        else
          echo "Proyecto ${{ github.event.repository.name }} fue creado exitosamente en sonarcloude"

          echo "Se establece rama main como rama por defecto"
          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
        fi

    - name: Enable execution gradle
      run: |
        chmod 777 gradlew

    - name: Run SonarQube analysis
      run: |
        ./gradlew sonarqube \
        -Dsonar.projectKey=${{ github.event.repository.name }} \
        -Dsonar.organization=dusankm \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.branch.name=feat-devsecops

    #- name: SonarQube Quality Gate Check
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #  uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
    #  with:
    #    scanMetadataReportFile: build/sonar/report-task.txt
        
#-----------------------SCA--------------------------------------
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        chmod 777 gradlew
        ./gradlew build

    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      env:
        JAVA_HOME: /opt/jdk
      id: Depcheck
      with:
        project: '${{ github.event.repository.name }}'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Upload Test result
      uses: actions/upload-artifact@master
      with:
        name: Depcheck report
        path: ${{github.workspace}}/reports
        
